package groupworkNamaste;

public class CategoryManagement extends SuperClassEmployee {
    
    //AUTOGENERATED - CHECK IF IT IS USABLE     
	private double bonusFactor;
        
	//METHOD FOR CALCULATING BONUS
	public void calculateBonus() {
	}	
    //end of autogenerated things 
	
	
	
	
	
}//end class


