package groupworkNamaste;

public class CategoryManagement extends SuperClassEmployee {
    
    //AUTOGENERATED - CHECK IF IT IS USABLE     
	private double bonusFactor;
        
	public void calculateBonus() {
	}
	public void calculateSalary() {
	}
    //end of autogenerated things 
}
