package groupworkNamaste;

public class EmployeeStatistics {
    
    //AUTOGENERATED - CHECK IF IT IS USABLE
	private Enum choice;

	public void showEmployeeInformation() {
	}
    //end of autogenerated things  
	
	
	
	
	
}//end class
