package groupworkNamaste;

public class MainMenu {

    //AUTOGENERATED - CHECK IF IT IS USABLE
	private Enum choice; 

	public void main() {
	}

	public void exit() {
	}
    //end of autogenerated things    
}
