package groupworkNamaste;

public class MainMenu {

    //AUTOGENERATED - CHECK IF IT IS USABLE
	private Enum choice; 

	public void main() {
	}
	public void exit() {
	}
    //end of autogenerated things    
	
	//MAIN METHOD
	public static void main(String[] args){
		
		// CONTAINS TOP MENU 
		// 1) Management	>> Go to class EmployeeManagement
		// 2) Statistics	>> Go to class EmployeeStatistics
		// 3) Exit 		>> Done in this method
		
		
		
		
	}//end main 
	
}//end class
