package groupworkNamaste;

public abstract class SuperClassEmployee {
    
    //AUTOGENERATED - CHECK IF IT IS USABLE   
	private String name;
	//private Date personNumber; -  wrong somehow
	private Enum category;
	private double salary;
	private static int employeeID;
	private double bonus;
        
	public void calculateSalary() {
	}
	public void calculateBonus() {
	}
    //end of autogenerated things  
	
	
	//ABSTRACT METHOD FOR CALCULATING BONUS
	
	
}//end class
